on:
  script:
    github_token: ${{secrets.GITHUB_TOKEN}}
    config:
      limit: 999
    path: ./workflows/bls.js
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.script.outputs.title}}
          secrets: ${{toJSON(secrets)}}
        run: |
          echo title: $title