on:
  script:
    github_token: ${{secrets.GITHUB_TOKEN}}
    config:
      limit: 999
      debug: true
    path: ./workflows/bls.js
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        with:
          secrets: ${{ toJSON(secrets) }}
        env:
          secrets: ${{ toJSON(secrets) }}
          title: ${{on.script.outputs.title}}
        run: |
          echo title: $title